### ISSUE TITLE
Los version 1.3 charges extremely slow

### ISSUE THREAD

**Issue by Turbolqk** [whatawurst/android_device_sony_yoshino-common#102]
Dirty-flashing from 1.2, charging seems to be extremely slow. The current is around 700mA when charging rapidly and the phone heats up very fast. 
It took me 4 hours and a half to get from 10% to 100%. 
Perhaps it's somehow connected to the Battery Care feature.
https://github.com/whatawurst/android_device_sony_yoshino-common/issues/3 - this is a good report on how the current should behave.

**Comment by derfelot** [comment]
Strange, 1.3 seems to charge just like the previous version for me. Maybe try resetting the charge control settings (top right "circle arrow").

**Comment by Turbolqk** [comment]
I tried that, but when charging again, the current is constantly capped at around 700mA. I check magisk modules and maybe clean reflash the rom.

**Comment by Turbolqk** [comment]
I reflashed the rom clean and all is good now. No idea what the problem was, but I'm probably an exception, since nobody else complained at this point.
