### ISSUE TITLE
Booting 1.3 version

### ISSUE THREAD

**Issue by Turbolqk** [whatawurst/android_device_sony_yoshino-common#103]
For some reason when booting the OS since the last update, the animation stops, the screen goes black, then the animation starts again until the phone finally boots. 
Not a big issue, but it might be useful to note, who knows.

**Comment by derfelot** [comment]
I am not having this issue, neither on lilac, nor on poplar. Both were dirty flashed with 1.3. I would need a log to see what might be the issue on your end - provided you aren't using Gapps other than MTG or random Magisk modules that might be a reason for this. I don't want to invest too much time figuring out issues with 3rd party modifications.

**Comment by Turbolqk** [comment]
You are right. I reflashed Magisk and the problem went away. Thanks!
