### ISSUE TITLE
Fixup camera broken in Android U

### ISSUE THREAD

**Issue by RedSTARO** [whatawurst/android_device_sony_yoshino-common#108]
Pick commit below to fix: https://github.com/RedSTARO/android_device_sony_yoshino-common_miku/commit/a8413853eed9d6a83e9fdcf8b1f6b59f62b676ac

After patched blobs are in the PR here: https://github.com/whatawurst/android_vendor_sony_yoshino-common/pull/5

**Comment by derfelot** [comment]
Initial bring-up is done.
