### ISSUE TITLE
Issue while signing build (temporary fix provided)

### ISSUE THREAD

**Issue by erredi** [whatawurst/android_device_sony_yoshino-common#109]
With last update while signing build with the command sign_target_files_apks an error occurred:

"Error: could not load context file from out/target/product/poplar/obj/ETC/file_contexts.bin_intermediates/file_contexts.device.tmp"

A temporary fix provided by @jw96 is to comment line 106 of the file sepolicy/vendor/file_contexts

line 106: #sys/devices/virtual/graphics/fb([0-3])+/idle_state             u:object_r:sysfs_graphics:s0

Is it necessary to comment out this line of code or can it be solved differently?

**Comment by erredi** [comment]
there is a typo, the error doesn't happen during the build signing process, but during the build itself!

**Comment by petefoth** [comment]
I am hitting the same problem. A long-term fix would be very welcome :)

**Comment by derfelot** [comment]
Hello,

I've been quite busy in the last month or so. I will provide a new A13 build very soon (and fix any issues that have come up since then for building) and will then move to A14.

**Comment by derfelot** [comment]
Fixed with https://github.com/whatawurst/android_device_sony_yoshino-common/commit/10bfcf75da44b1729dceff23b088714433b84cad
