### ISSUE TITLE
Audio playback stops at the end of the current track

### ISSUE THREAD

**Issue by petefoth** [whatawurst/android_device_sony_yoshino-common#115]
Playing a music track via any music player [^1], playback stops at the end of the track being played. The next track in the queue has to be manually started, instead of playing automatically.

This is a known bug in LineageOS in several devices [^2], and is easily fixable
- in code [^3]
- via adb
```
adb root
adb shell "mount -o rw,remount /vendor"
adb shell "sed -i '/debug.stagefright.omx_default_rank.sw-audio/d' /vendor/build.prop"
adb reboot
```

I have reproduced the issue, and applied the adb fix on recent los4microG builds for `lilac` & `poplar_dsds`

The file to change for yoshino devices is [`vendor.prop`](https://github.com/whatawurst/android_device_sony_yoshino-common/blob/cad13bac4023688790a1ca265c85774864f09ac3/vendor.prop#L150)

[^1]: I have reproduced using Vanilla Music, Fossify Music Player, Auxio
[^2]: [`gts4lv` devices](https://gitlab.com/LineageOS/issues/android/-/issues/7107), [`sdm845-common` devices](https://gitlab.com/LineageOS/issues/android/-/issues/7103)
[^3]: [here](https://review.lineageos.org/c/LineageOS/android_device_samsung_gts4lv-common/+/391819) & [here](https://review.lineageos.org/c/LineageOS/android_device_xiaomi_sdm845-common/+/391833)

**Comment by derfelot** [comment]
Thanks, added the change with https://github.com/whatawurst/android_device_sony_yoshino-common/commit/38ab9639f8517c6b44b0b1728177bfa354449987 (didn't actually build and test).

**Comment by petefoth** [comment]
Thanks I'll make some los4microg builds

**Comment by bo-hmpl** [comment]
Thank you @petefoth ! This resolved an issue with PodcastAddict where at the end of a track there was a toast message `Audio service error. Please restart your device [...]` with a corresponding log entry `MediaCodecDecoderException: Decoder failed: OMX.google.mp3.decoder` while the file wasn't removed from playlist and deleted (as set up in PA).

Restarting didn't resolve this, of course. Your patch did. :)
