### ISSUE TITLE
Baseband  issuse

### ISSUE THREAD

**Issue by shuxiangfan** [whatawurst/android_device_sony_yoshino-common#37]
Hello, I built Pixel Experience Plus with latest device trees for maple. But after I booted up, it couldn't detect SIM card and said **Unknown Baseband version**. I have tried to revert 0e509117757ff7c7ac0fba385d0c511ea8609f7d but nothing changed. Here's my logcat:[https://del.dog/tolataleve](url)
I noticed `Could not find 'android.hardware.radio@1.1::IRadio/slot1' for ctl.interface_start from pid: 636 (/system/bin/hwservicemanager)` and `Could not find 'android.hardware.secure_element@1.0::ISecureElement/SIM1' for ctl.interface_start from pid: 636 (/system/bin/hwservicemanager)`

**Comment by shank03** [comment]
Other ROMs it worked right ?

**Comment by sharakovia** [comment]
Rcmiku built evox with latest device trees and got same problem.

**Comment by shuxiangfan** [comment]
> Other ROMs it worked right ?

No, Rcmiku built evox with latest device trees and got same problem.

**Comment by derfelot** [comment]
my guess would be that those other roms dont have secureelement support. remove it from the manifest and see if that fixes it.

but i'm not sure what the issue is here exactly. los is working fine.

**Comment by derfelot** [comment]
actually, that might not be the issue in the end. try posting a full logcat to have a look at.

**Comment by derfelot** [comment]
actually, that is probably not the issue. the link to you logcat isnt working for me (copy/pasting the url isn't either). upload it again so we can have a look

edit: nevermind, just took a while to come up

edit2: Try what i mentioned above, just to rule this out.

**Comment by shuxiangfan** [comment]
> my guess would be that those other roms dont have secureelement support. remove it from the manifest and see if that fixes it.
> 
> but i'm not sure what the issue is here exactly. los is working fine.

Thanks a lot! I will try a clean build later. This is log file: https://www.dropbox.com/s/lk03269azojnzqm/log.log?dl=0

**Comment by derfelot** [comment]
Right, i missed the fact that you are running maple.

I see the problem. I'll try to fix his later.

**Comment by derfelot** [comment]
should be fixed in my lineage-18.1_update branches

**Comment by shuxiangfan** [comment]
I saw commit 5ced017768936efb1de6ae6fa7559d486058dc0b in your maple_dsds_update and after applying it ,baseband works! Thank you for your great work!

**Comment by derfelot** [comment]
cool, i close this issue then

**Comment by lucasponez** [comment]
> I saw commit 5ced017768936efb1de6ae6fa7559d486058dc0b in your maple_dsds_update and after applying it ,baseband works! Thank you for your great work!

Do you have the link of this commit, friend?

**Comment by shuxiangfan** [comment]
> > I saw commit 5ced017768936efb1de6ae6fa7559d486058dc0b in your maple_dsds_update and after applying it ,baseband works! Thank you for your great work!
> 
> Do you have the link of this commit, friend?

https://github.com/whatawurst/android_device_sony_maple_dsds/commit/c011bdf7be633be6b63133f787c0276a51e086bd 
Here is it.
