### ISSUE TITLE
hardware/qcom-caf/msm8998 missing

### ISSUE THREAD

**Issue by TechnoHT** [whatawurst/android_device_sony_yoshino-common#67]
LOS 19
`In file included from device/sony/poplar_kddi/Android.mk:20:
In file included from device/sony/yoshino-common/Android.mk:21:
In file included from device/sony/yoshino-common/hardware/Android.mk:19:
device/sony/yoshino-common/hardware/qcom-caf/Android.mk:6: error: hardware/qcom-caf/msm8998/audio/Android.mk: No such file or directory
13:34:00 ckati failed with: exit status 1`

And indeed it's missing (exist on older branch like 18.1 nor 17) or deprecated.
on 18.1 it's a symlink so I'm not sure if this is required.

**Comment by TechnoHT** [comment]
Closed as if those files were not synced correctly until I rebuilt git with OpenSSL

**Comment by derfelot** [comment]
They are not tracked yet:
https://review.lineageos.org/c/LineageOS/android/+/323434
